// Product catalogue for the Mishri demo store.
// Prices are in INR per box. Images live in ./images (fetched once from loremflickr keyword search).
const PRODUCTS = [
  {
    id: "kaju-katli",
    name: "Kaju Katli",
    category: "Barfi",
    price: 649,
    weight: "500 g",
    tag: "Bestseller",
    desc: "Thin diamonds of cashew and sugar, finished with edible silver leaf. Melts before you finish the bite.",
    img: "images/kaju-katli.jpg",
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    category: "Syrup",
    price: 349,
    weight: "12 pieces",
    tag: "",
    desc: "Khoya dumplings fried slow and soaked in rose and cardamom syrup. Served warm at the counter.",
    img: "images/gulab-jamun.jpg",
  },
  {
    id: "rasmalai",
    name: "Rasmalai",
    category: "Bengali",
    price: 429,
    weight: "8 pieces",
    tag: "Chilled",
    desc: "Soft chenna discs resting in saffron milk, topped with pistachio. Keep cold, eat within two days.",
    img: "images/rasmalai.jpg",
  },
  {
    id: "motichoor-ladoo",
    name: "Motichoor Ladoo",
    category: "Ladoo",
    price: 399,
    weight: "500 g",
    tag: "",
    desc: "Tiny boondi pearls bound with ghee and sugar. The one that shows up at every celebration.",
    img: "images/motichoor-ladoo.jpg",
  },
  {
    id: "pista-barfi",
    name: "Pista Barfi",
    category: "Barfi",
    price: 749,
    weight: "500 g",
    tag: "Premium",
    desc: "Ground Iranian pistachio and milk solids pressed into a dense green slab. No colour added.",
    img: "images/pista-barfi.jpg",
  },
  {
    id: "mysore-pak",
    name: "Mysore Pak",
    category: "Ghee",
    price: 449,
    weight: "500 g",
    tag: "",
    desc: "Besan, sugar and a generous amount of ghee, cooked until it crumbles on the tongue.",
    img: "images/mysore-pak.jpg",
  },
  {
    id: "jalebi",
    name: "Jalebi",
    category: "Syrup",
    price: 249,
    weight: "400 g",
    tag: "Made to order",
    desc: "Crisp fermented batter spirals dipped in warm saffron syrup. Best eaten the same day.",
    img: "images/jalebi.jpg",
  },
  {
    id: "rasgulla",
    name: "Rasgulla",
    category: "Bengali",
    price: 329,
    weight: "12 pieces",
    tag: "",
    desc: "Spongy chenna balls in light sugar syrup. Cold, clean and not too sweet.",
    img: "images/rasgulla.jpg",
  },
  {
    id: "besan-ladoo",
    name: "Besan Ladoo",
    category: "Ladoo",
    price: 379,
    weight: "500 g",
    tag: "",
    desc: "Roasted gram flour, ghee and cardamom rolled by hand. Nutty, grainy, comforting.",
    img: "images/besan-ladoo.jpg",
  },
  {
    id: "kalakand",
    name: "Kalakand",
    category: "Ghee",
    price: 499,
    weight: "500 g",
    tag: "",
    desc: "Soft, grainy squares of curdled milk and sugar, set overnight and cut by hand.",
    img: "images/kalakand.jpg",
  },
  {
    id: "moong-dal-halwa",
    name: "Moong Dal Halwa",
    category: "Ghee",
    price: 449,
    weight: "500 g",
    tag: "Winter special",
    desc: "Moong dal roasted slowly in ghee until it turns golden, then finished with saffron and almonds.",
    img: "images/moong-dal-halwa.jpg",
  },
  {
    id: "kesar-peda",
    name: "Kesar Peda",
    category: "Barfi",
    price: 549,
    weight: "500 g",
    tag: "",
    desc: "Slow-cooked khoya pressed into saffron discs, each one stamped by hand.",
    img: "images/kesar-peda.jpg",
  },
];

// Rough serving guidance shown on cards. Demo values.
const SERVES = { "500 g": "serves 8 to 10", "400 g": "serves 6 to 8", "12 pieces": "serves 6", "8 pieces": "serves 4" };

const GIFT_BOXES = [
  {
    id: "box-diwali",
    name: "The Diwali Box",
    price: 1899,
    weight: "1.2 kg, 6 varieties",
    desc: "Kaju Katli, Pista Barfi, Motichoor Ladoo, Kesar Peda, Besan Ladoo and Kalakand in a wooden box.",
    img: "images/box-diwali.jpg",
  },
  {
    id: "box-office",
    name: "The Office Box",
    price: 1299,
    weight: "800 g, 4 varieties",
    desc: "Dry sweets only, so nothing melts on the desk. Feeds a team of ten.",
    img: "images/box-office.jpg",
  },
  {
    id: "box-wedding",
    name: "The Wedding Favour",
    price: 249,
    weight: "4 pieces per box",
    minQty: 50,
    step: 10,
    desc: "Two Kaju Katli and two Kesar Peda in a small ribboned box. Minimum order of 50.",
    img: "images/box-wedding.jpg",
  },
];
