// The product, category, policy and tracking pages are generated by
// build.js from index.html, products.js and policies.js. This fails when
// someone edits those and forgets to run `node build.js`.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { ROOT } from "./helpers/harness.mjs";

const GENERATED = ["sweets", "gifts", "mithai", "policies", "track"];
const pagesIn = (root) =>
  GENERATED.flatMap((dir) => (fs.existsSync(path.join(root, dir)) ? fs.readdirSync(path.join(root, dir), { recursive: true }) : []).map((f) => path.join(dir, f)))
    .filter((f) => f.endsWith("index.html"))
    .sort();
const locs = (xml) => [...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map((m) => m[1]);

test("generated pages match their sources", () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "mishri-build-"));
  try {
    for (const f of ["build.js", "index.html", "products.js", "policies.js"]) fs.copyFileSync(path.join(ROOT, f), path.join(tmp, f));
    // Share images and their sizes come from the photographs themselves.
    fs.cpSync(path.join(ROOT, "images"), path.join(tmp, "images"), { recursive: true });
    execFileSync(process.execPath, ["build.js"], { cwd: tmp, stdio: "pipe" });

    const fresh = pagesIn(tmp);
    assert.deepEqual(pagesIn(ROOT), fresh, "the same set of pages");
    for (const f of fresh) {
      const committed = fs.readFileSync(path.join(ROOT, f), "utf8");
      assert.ok(committed === fs.readFileSync(path.join(tmp, f), "utf8"), `${f} is out of date: run node build.js`);
    }
    // lastmod is the build date, so compare only the URLs.
    assert.deepEqual(locs(fs.readFileSync(path.join(ROOT, "sitemap.xml"), "utf8")), locs(fs.readFileSync(path.join(tmp, "sitemap.xml"), "utf8")));
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

test("every internal link on a generated page points at a real file", () => {
  const broken = [];
  for (const f of ["index.html", ...pagesIn(ROOT)]) {
    const html = fs.readFileSync(path.join(ROOT, f), "utf8");
    for (const [, href] of html.matchAll(/(?:href|src)="([^"#?]+)[^"]*"/g)) {
      if (/^(https?:|mailto:|tel:|data:|\/_vercel\/)/.test(href)) continue;
      let target = href.startsWith("/") ? path.join(ROOT, href) : path.resolve(path.dirname(path.join(ROOT, f)), href);
      if (href.endsWith("/")) target = path.join(target, "index.html");
      // /api/* are functions, not files.
      if (path.relative(ROOT, target).startsWith("api" + path.sep)) target += ".js";
      if (!fs.existsSync(target)) broken.push(`${f}: ${href}`);
    }
  }
  assert.deepEqual(broken, []);
});
