#!/usr/bin/env python3
"""Builds vendor/phosphor/: the Phosphor icon fonts (light and fill), cut
down to the icons the site uses, so pages load a few KB from the site
itself instead of ~290 KB of fonts from unpkg.com.

Re-run after using a new icon (tests/build.test.mjs fails until you do):

    pip install fonttools brotli
    python3 tools/build-icons.py

It downloads @phosphor-icons/web from npm, finds every `ph-<name>` class in
the site's HTML and JS, and writes icons.css plus one small woff2 per weight.
"""
import os
import re
import subprocess
import sys
import tarfile
import tempfile

from fontTools import subset

VERSION = "2.1.1"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "vendor", "phosphor")
WEIGHTS = {"light": "Phosphor-Light", "fill": "Phosphor-Fill"}
SOURCES_SKIP = {"vendor", "node_modules", ".git", ".vercel", "tests", "tools"}
NOT_ICONS = {"ph-light", "ph-fill", "ph-bold", "ph-thin", "ph-duotone"}


def used_icons():
    names = set()
    for folder, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SOURCES_SKIP]
        for f in files:
            if f.endswith((".html", ".js")):
                with open(os.path.join(folder, f), encoding="utf-8") as fh:
                    names.update(re.findall(r"\bph-[a-z0-9]+(?:-[a-z0-9]+)*", fh.read()))
    return sorted(names - NOT_ICONS)


def fetch_package(tmp):
    subprocess.run(["npm", "pack", f"@phosphor-icons/web@{VERSION}", "--silent"], cwd=tmp, check=True, stdout=subprocess.DEVNULL)
    tgz = next(f for f in os.listdir(tmp) if f.endswith(".tgz"))
    with tarfile.open(os.path.join(tmp, tgz)) as t:
        t.extractall(tmp, filter="data")
    return os.path.join(tmp, "package", "src")


def main():
    icons = used_icons()
    os.makedirs(OUT, exist_ok=True)
    css = [f"/* Phosphor Icons {VERSION} (MIT, phosphoricons.com), cut down to the icons this site uses.\n"
           "   Generated by tools/build-icons.py: do not edit by hand. */\n"]
    with tempfile.TemporaryDirectory() as tmp:
        src = fetch_package(tmp)
        for weight, family in WEIGHTS.items():
            full = open(os.path.join(src, weight, "style.css"), encoding="utf-8").read()
            codes = {}
            for name in icons:
                m = re.search(r"\.ph-%s\.%s:before\s*\{\s*content:\s*\"\\([0-9a-f]+)\"" % (weight, re.escape(name)), full)
                if not m:
                    sys.exit(f"{name} is not a Phosphor icon (checked the {weight} weight)")
                codes[name] = m.group(1)

            options = subset.Options()
            options.flavor = "woff2"
            options.layout_features = []  # the CSS uses code points, not ligatures
            options.name_IDs = ["*"]
            font = subset.load_font(os.path.join(src, weight, f"{family}.woff2"), options)
            sub = subset.Subsetter(options)
            sub.populate(unicodes=[int(c, 16) for c in codes.values()])
            sub.subset(font)
            subset.save_font(font, os.path.join(OUT, f"{weight}.woff2"), options)

            css.append(f"""
@font-face {{
  font-family: "{family}";
  src: url("{weight}.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}}
.ph-{weight} {{
  font-family: "{family}" !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}}
""")
            css.extend(f'.ph-{weight}.{name}:before {{ content: "\\{code}"; }}\n' for name, code in codes.items())

        with open(os.path.join(src, "..", "LICENSE"), encoding="utf-8") as fh:
            open(os.path.join(OUT, "LICENSE"), "w", encoding="utf-8").write(fh.read())
    open(os.path.join(OUT, "icons.css"), "w", encoding="utf-8").write("".join(css))
    sizes = ", ".join(f"{w} {os.path.getsize(os.path.join(OUT, w + '.woff2')) // 1024 + 1} KB" for w in WEIGHTS)
    print(f"{len(icons)} icons: {sizes}")


if __name__ == "__main__":
    main()
